version: '3'
services:
  mongodb:
    build: ./MongoDB
    image: mongodb
    container_name: "mongodb"
    ports:
      - 27017:27017

  gRPC_client:
    build: ./gRPC_client
    image: grpc_client
    container_name: "gRPC_client"
    volumes:
      - ~/Dropbox/workshop/:/workshop      
    depends_on:
      - alertmanager

  alertmanager:
    build: ./AlertManager
    image: alertmanager
    container_name: "alertmanager"
    #ports: 
      #- 8001:8001
    volumes:
      - ~/Dropbox/workshop/:/workshop
    #links:
    #  - mongodb
    depends_on:
      - mongodb


  ui:
    build: ./UI
    image: ui
    container_name: "ui"
    ports: 
      - 8000:8000
      - 5000:5000
    volumes:
      - ~/Dropbox/workshop/:/workshop
    #links:
    #  - mongodb
    #  - alertmanager
    #  - gRPC_client
    #depends_on:
    #  - mongodb
    #  - alertmanager
    #  - gRPC_client
