version: '3'
services:
  mongodb:
    build: ./MongoDB
    image: mongodb
    container_name: "mongodb"
    ports:
      - 27017:27017

  gRPCServer:
    build: ./gRPC_server
    image: grpc_server
    container_name: "gRPC_server"
    ports:
      - 8003:8003
      - 8001:8001
    volumes:
      - ~/Dropbox/workshop/:/workshop      

  alertmanager:
    build: ./AlertManager
    image: alertmanager
    container_name: "alertmanager"
    ports: 
      - 8001:8001
    volumes:
      - ~/Dropbox/workshop/:/workshop
    links:
      - mongodb
      - gRPCServer
    depends_on:
      - mongodb
      - gRPCServer

  ui:
    build: ./UI
    image: ui
    container_name: "ui"
    ports: 
      - 8000:8000
    volumes:
      - ~/Dropbox/workshop/:/workshop
    links:
      - mongodb
      - alertmanager
      - gRPCServer
    depends_on:
      - mongodb
      - alertmanager
      - gRPCServer
