version: '3'
services: 
  mist:
    image: hydrosphere/mist:1.0.0-RC17-2.3.0
    container_name: "hydrosphere_mist"
    ports:
     - 2004:2004
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock

  mist_cli:
    build: ../cli_docker
    image: mist_cli
    container_name: "mist_cli"
    ports: 
      - 8001:8001
    volumes:
     - ~/Dropbox/workshop/SparkMist/:/app
    depends_on:
      - mist
      - spark_sandbox

  spark_sandbox:
    build: ./SparkSandbox_docker
    image: spark_sandbox
    container_name: "spark_sandbox"
    ports: 
      - 8003:8003
      - 4040:4040
    volumes:
     - ~/Dropbox/workshop/SparkMist/:/app
    environment:
     - SPARK_PUBLIC_DNS=0.0.0.0
